### PR TITLE
Inherit PATH in systemd services

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@tejohnso @fjvallarino I found an issue with our services which causing the github webhook to fail.

This problem was causing git pulls to fail, and it couldalso cause other commands to fail in the future if not fixed.

### CODE REVIEW

**Comment by tejohnso** [comment]
@ahmedalsudani can we avoid overwriting that and leave it at whatever the default is? Does it default to nothing?

**Comment by ahmedalsudani** [comment]
@tejohnso we might be able to, but I followed the precedent in `display-messaging-service.service`. 

I will test not setting PATH altogether.

**Comment by ahmedalsudani** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
